before:
  hooks:
    - go mod download
builds:
  -
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - CHANGELOG.md
      - README.md
      - LICENSE
      - VERSION
      - charts/**/*
      - config/**/*
      - templates/**/*
      - docs/**/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge:'
release:
  prerelease: auto
  draft: true
