base:
    deploymentName: jenkins-controller
    domain: test-jenkins1domain.tld
    jenkinsURIPrefix: /jenkins
    ipAddress: 0.0.0.0
    namespace: test-jenkins1
jcasc:
    clouds: {}
    credentialIDs:
        docker: docker-registry-credentialsid
        maven: repository-credentialsid
        npm: repository-credentialsid
        vcs: vcs-notification-credentialsid
    jobsConfig:
        seedJobRepository: https://github.com/Ragin-LundF/jenkins-jobdsl-remote.git
        jobsDefinitionRepository: https://github.com/B2BInternetSolutions/b2b--infrastructure--autoscaled-eks-cluster--v03--jenkins-jobs.git
    securityRealm:
        localUsers:
            adminPassword: $2a$04$UNxiNvJN6R3me9vybVQr/OzpMhgobih8qbxDpGy3lZmmmwc6t48ty
            userPassword: $2a$04$BFPq6fSa9KGKrlIktz/C8eSFrrG/gglnW1eXWMSjgtCSx36mMOSNm
    systemMessage: Mike - Jenkins Test 2
jenkinsHelmValues:
    controller:
        image: jenkins/jenkins
        tag: lts
        imagePullPolicy: Always
        customJenkinsLabel: jenkins-controller-for-seed
        authorizationStrategyAllowAnonymousRead: "true"
        adminPassword: admin
        sidecarsConfigAutoReloadFolder: https://raw.githubusercontent.com/B2BInternetSolutions/k8s-jcasc-management-go/master/projects/test-jenkins1/jcasc_config.yaml
        #sidecarsConfigAutoReloadFolder: https://raw.githubusercontent.com/Ragin-LundF/k8s-jcasc-project-config/main/test-jenkins1/jcasc_config.yaml
    persistence:
        accessMode: ReadWriteOnce
        storageSize: 2Gi
        storageClass: k8s-storage-class--efs
    additionalNamespaces:
        - test-jenkins1--preview
        - test-jenkins1--production
        - test-jenkins1--qa
persistentVolumeClaim:
    pvcSpec:
        accessMode: ReadWriteOnce
        storageClassName: k8s-storage-class--efs
        resources:
            storageSize: 2Gi
nginx:
    ingress:
        annotationIngressClass: nginx
        deploymentName: nginx-ingress
        containerImage: bitnami/nginx-ingress-controller:latest
    loadBalancer:
        enabled: false
        annotations:
            externalDNSHostName: domain.tld
            externalDNSTtl: 60
        ports:
            http:
                port: 80
                targetPort: 80
            https:
                port: 443
                targetPort: 443
