k8sJenkinsMgmt:
  ingress:
    annotationIngressClass: nginx
    namespace: test-jenkins2
    loadbalancerIp: 0.0.0.0
    deploymentName: nginx-ingress
    jenkinsDeploymentName: jenkins-controller
    jenkinsUriPrefix: /jenkins
    containerImage: bitnami/nginx-ingress-controller:latest
    imagePullSecrets: 
    controllerForNamespace:
      enabled: false
  loadbalancer:
    enabled: false
    ports:
      http:
        port: 80
        targetPort: 80
      https:
        port: 443
        targetPort: 443
    annotations:
      enabled: false
      external_dns_hostname: "0.0.0.0"
      external_dns_ttl: 60
